baseURL = "https://saasify-demo.chaoming.li/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
theme = "hugo-saasify-theme"

# Language configuration
[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    title = "Saasify"
    weight = 1
    contentDir = "content"

  [languages.zh-cn]
    languageCode = "zh-cn"
    languageName = "简体中文"
    title = "Saasify"
    weight = 2
    contentDir = "content/zh-cn"

# Enable syntax highlighting (moved to markup.highlight section below for modern Hugo)
# pygmentsCodeFences = true
# pygmentsUseClasses = true

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod
enableGitInfo = true

# Enable taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Pagination
paginate = 6
paginatePath = "page"

[params]
  description = ""
  author = "Chaoming Li"
  logo = "/images/logo.svg"
  googleAnalytics = "G-E6RMRJ4HQ3"
  
  # Social Media Links
  [params.social]
    linkedin = "https://linkedin.com/in/chaomingli"
    twitter = "https://twitter.com/lichaoming"
    youtube = "https://youtube.com/@chaomingli"
    facebook = "https://facebook.com/lichaoming"
    instagram = "https://instagram.com/lichaoming"
    github = "https://github.com/chaoming"
  
  # Footer Configuration
  [params.footer]
    column_1_title = "Features"
    column_2_title = "COMPANY"
    column_3_title = "LEGAL"
  
  [params.header]
    # Header background and border styles (optional)
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Logo configuration
    [params.header.logo]
      src = "/images/logo.svg"
    
    # Menu configuration
    [params.header.menu]
      spacing = "space-x-8"
      
      # Dropdown menu configuration
      [params.header.menu.dropdown]
        width = "w-72"
        container_padding = "py-6"
        item_padding = "px-8 py-3"
        background = "bg-white"
        border = "border border-gray-100"
        shadow = "shadow-xl"
        radius = "rounded-lg"
        text_color = "text-gray-700"
        hover_background = "hover:bg-gray-50"
        text_size = "text-sm"
    
    # Button configuration
    [params.header.buttons]
      # Sign In button
      [params.header.buttons.signIn]
        text = "Sign in"
        url = "/signin"
      
      # Get Started button
      [params.header.buttons.getStarted]
        text = "Get Started"
        url = "/get-started"

  # Blog configuration
  [params.blog]
    enable = true
    title = "Latest Articles"
    subtitle = "Learn more about web development and best practices"
    
    # Blog CTA configuration
    [params.blog.cta]
      enable = true  # Enable/disable CTA in blog posts
    
    # Sidebar configuration
    [params.blog.sidebar]
      # Recent articles section
      [params.blog.sidebar.recent]
        enable = true
        count = 5

      # Categories section
      [params.blog.sidebar.categories]
        enable = true

      # Tags section
      [params.blog.sidebar.tags]
        enable = true
        count = 20

      # Subscribe form section
      [params.blog.sidebar.subscribe]
        enable = true
        action = "https://formspree.io/f/your-form-id"
        emailName = "email"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[build]
  writeStats = true

[build.buildStats]
  enable = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$']

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# English language specific params
[languages.en.params]
  # Global CTA Configuration
  [languages.en.params.cta]
    enable = true
    title = "Ready to Build Your SaaS Website?"
    description = "Join companies already using our theme to create beautiful, high-performance websites."
    gradient_from = "#2563eb"  # Indigo-600
    gradient_to = "#7c3aed"    # Purple-600
    gradient_angle = 30
    [languages.en.params.cta.primary_button]
      text = "Get Started Free"
      url = "/get-started"
    [languages.en.params.cta.secondary_button]
      text = "Book Demo"
      url = "/demo"

  # Footer Configuration
  [languages.en.params.footer]
    column_1_title = "Features"
    column_2_title = "COMPANY"
    column_3_title = "LEGAL"

  # Header Configuration
  [languages.en.params.header]
    [languages.en.params.header.buttons]
      [languages.en.params.header.buttons.signIn]
        text = "Sign in"
        url = "/signin"
      [languages.en.params.header.buttons.getStarted]
        text = "Get Started"
        url = "/get-started"

  # Blog configuration
  [languages.en.params.blog]
    enable = true
    title = "Latest Articles"
    subtitle = "Learn more about web development and best practices"

# Chinese language specific params
[languages.zh-cn.params]
  # Global CTA Configuration
  [languages.zh-cn.params.cta]
    enable = true
    title = "准备好构建您的 SaaS 网站了吗？"
    description = "加入已经使用我们主题创建精美、高性能网站的公司。"
    gradient_from = "#2563eb"  # Indigo-600
    gradient_to = "#7c3aed"    # Purple-600
    gradient_angle = 30
    [languages.zh-cn.params.cta.primary_button]
      text = "免费开始"
      url = "/zh-cn/get-started"
    [languages.zh-cn.params.cta.secondary_button]
      text = "预约演示"
      url = "/zh-cn/demo"

  # Footer Configuration
  [languages.zh-cn.params.footer]
    column_1_title = "功能特性"
    column_2_title = "公司"
    column_3_title = "法律"

  # Header Configuration
  [languages.zh-cn.params.header]
    [languages.zh-cn.params.header.buttons]
      [languages.zh-cn.params.header.buttons.signIn]
        text = "登录"
        url = "/zh-cn/signin"
      [languages.zh-cn.params.header.buttons.getStarted]
        text = "开始使用"
        url = "/zh-cn/get-started"

  # Blog configuration
  [languages.zh-cn.params.blog]
    enable = true
    title = "最新文章"
    subtitle = "了解更多关于网站开发和最佳实践的内容"

# English Navigation Menu
[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Features"
    weight = 1
    [languages.en.menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Performance", url = "/features/performance/" },
        { name = "Design System", url = "/features/design-system/" },
        { name = "Developer Experience", url = "/features/developer-experience/" }
      ]
  [[languages.en.menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 2
  [[languages.en.menu.main]]
    name = "Docs"
    url = "/docs"
    weight = 3
  [[languages.en.menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4
  [[languages.en.menu.main]]
    name = "Company"
    weight = 5
    [languages.en.menu.main.params]
      has_submenu = true
      submenu = [
        { name = "About Us", url = "/company/" },
        { name = "Careers", url = "/careers/" }
      ]

  # Footer Column 1 Menu
  [[languages.en.menu.footer_column_1]]
    name = "Performance"
    url = "/features/performance/"
    weight = 1
  [[languages.en.menu.footer_column_1]]
    name = "Design System"
    url = "/features/design-system/"
    weight = 2
  [[languages.en.menu.footer_column_1]]
    name = "Developer Experience"
    url = "/features/developer-experience/"
    weight = 3

  # Footer Column 2 Menu
  [[languages.en.menu.footer_column_2]]
    name = "Blog"
    url = "/blog"
    weight = 1
  [[languages.en.menu.footer_column_2]]
    name = "About Us"
    url = "/company"
    weight = 2
  [[languages.en.menu.footer_column_2]]
    name = "Careers"
    url = "/careers"
    weight = 3

  # Footer Column 3 Menu
  [[languages.en.menu.footer_column_3]]
    name = "License"
    url = "/license"
    weight = 1
  [[languages.en.menu.footer_column_3]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 2

# Chinese Navigation Menu
[languages.zh-cn.menu]
  [[languages.zh-cn.menu.main]]
    name = "功能特性"
    weight = 1
    [languages.zh-cn.menu.main.params]
      has_submenu = true
      submenu = [
        { name = "性能优化", url = "/zh-cn/features/performance/" },
        { name = "设计系统", url = "/zh-cn/features/design-system/" },
        { name = "开发体验", url = "/zh-cn/features/developer-experience/" }
      ]
  [[languages.zh-cn.menu.main]]
    name = "价格"
    url = "/zh-cn/pricing"
    weight = 2
  [[languages.zh-cn.menu.main]]
    name = "文档"
    url = "/zh-cn/docs"
    weight = 3
  [[languages.zh-cn.menu.main]]
    name = "博客"
    url = "/zh-cn/blog"
    weight = 4
  [[languages.zh-cn.menu.main]]
    name = "公司"
    weight = 5
    [languages.zh-cn.menu.main.params]
      has_submenu = true
      submenu = [
        { name = "关于我们", url = "/zh-cn/company/" },
        { name = "招聘信息", url = "/zh-cn/careers/" }
      ]

  # Footer Column 1 Menu
  [[languages.zh-cn.menu.footer_column_1]]
    name = "性能优化"
    url = "/zh-cn/features/performance/"
    weight = 1
  [[languages.zh-cn.menu.footer_column_1]]
    name = "设计系统"
    url = "/zh-cn/features/design-system/"
    weight = 2
  [[languages.zh-cn.menu.footer_column_1]]
    name = "开发体验"
    url = "/zh-cn/features/developer-experience/"
    weight = 3

  # Footer Column 2 Menu
  [[languages.zh-cn.menu.footer_column_2]]
    name = "博客"
    url = "/zh-cn/blog"
    weight = 1
  [[languages.zh-cn.menu.footer_column_2]]
    name = "关于我们"
    url = "/zh-cn/company"
    weight = 2
  [[languages.zh-cn.menu.footer_column_2]]
    name = "招聘信息"
    url = "/zh-cn/careers"
    weight = 3

  # Footer Column 3 Menu
  [[languages.zh-cn.menu.footer_column_3]]
    name = "许可证"
    url = "/zh-cn/license"
    weight = 1
  [[languages.zh-cn.menu.footer_column_3]]
    name = "隐私政策"
    url = "/zh-cn/privacy"
    weight = 2
